### ISSUE TITLE
Build our own X

### ISSUE THREAD

**Issue by denibulkashvili** [chingu-voyages/v11-bears-team-16#3]
(programming language, front-end framework, etc etc dozens of them (https://github.com/danistefanovic/build-your-own-x))  Good for showcasing technical skills

**Comment by willjw3** [comment]
I like this one a lot. I've been thinking lately about creating a few npm packages that extend the functionalities of certain libraries or platforms.

**Comment by denibulkashvili** [comment]
@willjw3 which ones do you have in mind?

**Comment by willjw3** [comment]
Nothing in particular. For example, something like a charting library for a specific field. Say for someone building a fintech app, there would be a way of displaying data in charts (or otherwise) that would include symbols, colors, shapes that were highly relevant to the financial sector.
